# Generated by Django 4.0.5 on 2023-02-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0003_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('fileName', models.CharField(max_length=255, null=True)),
                ('dataUpload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='appproject.dataupload')),
            ],
        ),
    ]
