# Generated by Django 4.0.5 on 2023-03-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0006_alter_dataupload_metadataid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataupload',
            name='metaDataId',
        ),
    ]
