# Generated by Django 4.0.5 on 2023-03-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0007_remove_dataupload_metadataid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataupload',
            name='provinceId',
        ),
        migrations.AddField(
            model_name='dataupload',
            name='provinceName',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
