# Generated by Django 4.0.5 on 2023-03-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0010_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
