# Generated by Django 4.0.5 on 2023-03-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0011_alter_file_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='userRequestId',
            new_name='countView',
        ),
        migrations.RenameField(
            model_name='download',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='download',
            name='dataId',
        ),
        migrations.AddField(
            model_name='download',
            name='fileName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
