# Generated by Django 4.0.5 on 2023-03-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0012_rename_userrequestid_download_countview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='fileName',
            field=models.CharField(max_length=255),
        ),
    ]
