# Generated by Django 4.0.5 on 2023-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0013_alter_download_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agencyNameRequest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstnameUserRequest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastnameUserRequest',
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='dataName',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='fileName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
