# Generated by Django 4.0.5 on 2023-04-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0014_remove_user_agencynamerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='agencyName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
