# Generated by Django 4.0.5 on 2023-04-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0016_alter_dataupload_agencyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
