# Generated by Django 4.0.5 on 2023-04-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0017_dataupload_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
