# Generated by Django 4.0.5 on 2023-04-24 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appproject', '0018_alter_dataupload_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
